export const SHOW_CONFIG_MENU = 'CONFIG/SHOW_MENU'
export const HIDE_CONFIG_MENU = 'CONFIG/HIDE_MENU'
export const TOGGLE_COLOR_THEME = 'CONFIG/TOGGLE_THEME'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
